// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWSiaqsmeUfaB4YaK4CWFbmGfYUJwS_h4',
    appId: '1:180355594120:android:0c729784fbe98c39d42c3d',
    messagingSenderId: '180355594120',
    projectId: 'todo-list-provider-34f45',
    storageBucket: 'todo-list-provider-34f45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNE3ARg9-A9OfODTWnmf8RDw0FYbAAVUc',
    appId: '1:180355594120:ios:4f1a57842f9c0ecfd42c3d',
    messagingSenderId: '180355594120',
    projectId: 'todo-list-provider-34f45',
    storageBucket: 'todo-list-provider-34f45.appspot.com',
    androidClientId: '180355594120-ddd8qpf03ov6apuls41dj9ksv5poispn.apps.googleusercontent.com',
    iosClientId: '180355594120-8btmvuum4ess04b8qfmivv4g3vpchq7g.apps.googleusercontent.com',
    iosBundleId: 'br.com.stoica.todoList',
  );
}
